/**
 * Curated Reference Dataset for Country Evidence Intelligence & Verification Authorities
 * 
 * Note: This is purely a reference and test dataset used for development and local testing.
 * The production source of truth resides in the ServiceNow supporting tables:
 *   - u_bridge360_country
 *   - u_bridge360_country_document
 *   - u_bridge360_evidence_rule
 *   - u_bridge360_verification_authority
 *   - u_bridge360_verification_request
 */

import {
  CountryRecord,
  CountryDocumentRecord,
  EvidenceRuleRecord,
  VerificationAuthorityRecord,
  VerificationRequestRecord
} from '../types/bridge360';

export const INITIAL_COUNTRIES: CountryRecord[] = [
  {
    id: 'CTRY-AFG',
    countryName: 'Afghanistan',
    iso2: 'AF',
    iso3: 'AFG',
    nationality: 'Afghan',
    officialLanguages: 'Dari, Pashto',
    scriptsUsed: 'Arabic (Perso-Arabic)',
    transliterationNotes: 'Frequent variations in patronymic connectors and vowels (e.g., Mohammad/Muhammad, Khan, Wardak).',
    namingConvention: 'patronymic',
    civilRegistryInfo: 'National Statistics and Information Authority (NSIA) issues e-Tazkira. Paper Tazkira issued by local provincial registries.',
    active: true,
    notes: 'Paper Tazkira records often require provincial manual verification. E-Tazkira includes biometric QR verification.',
  },
  {
    id: 'CTRY-SYR',
    countryName: 'Syrian Arab Republic',
    iso2: 'SY',
    iso3: 'SYR',
    nationality: 'Syrian',
    officialLanguages: 'Arabic',
    scriptsUsed: 'Arabic',
    transliterationNotes: 'Al-/El- prefixes, diphthongs (Ou/O/U, Kh, Gh), French/English transliteration divergences.',
    namingConvention: 'tripartite',
    civilRegistryInfo: 'Civil Affairs Directorate under Ministry of Interior issues Family Book (Daftar A\'ila) and Individual Civil Status extracts.',
    active: true,
    notes: 'Family Book is primary authoritative evidence for household relationships and spousal union.',
  },
  {
    id: 'CTRY-UKR',
    countryName: 'Ukraine',
    iso2: 'UA',
    iso3: 'UKR',
    nationality: 'Ukrainian',
    officialLanguages: 'Ukrainian',
    scriptsUsed: 'Cyrillic',
    transliterationNotes: 'National passport transliteration standard (Resolution 55); patronymic suffix -ovych / -ivna.',
    namingConvention: 'tripartite',
    civilRegistryInfo: 'State Migration Service of Ukraine (SMS) and Diia digital register portal.',
    active: true,
    notes: 'Diia portal provides QR-verified digital extracts for internal passports and birth certificates.',
  },
  {
    id: 'CTRY-BGD',
    countryName: 'Bangladesh',
    iso2: 'BD',
    iso3: 'BGD',
    nationality: 'Bangladeshi',
    officialLanguages: 'Bengali',
    scriptsUsed: 'Bengali',
    transliterationNotes: 'Chowdhury/Choudhury, Hossain/Hussain, Rahman spelling variations.',
    namingConvention: 'family_surname',
    civilRegistryInfo: 'Office of the Registrar General, Birth and Death Registration (BDRIS) and National Identity Registration Wing (NIDW).',
    active: true,
    notes: 'Smart NID card features 10-digit unique identity number. BDRIS provides 17-digit online birth registration certificate.',
  },
  {
    id: 'CTRY-MMR',
    countryName: 'Myanmar',
    iso2: 'MM',
    iso3: 'MMR',
    nationality: 'Burmese / Myanmar',
    officialLanguages: 'Burmese',
    scriptsUsed: 'Burmese',
    transliterationNotes: 'Honorific prefixes (U, Daw, Ko, Ma) often conflated with given names. Mononymic naming common.',
    namingConvention: 'single_name',
    civilRegistryInfo: 'Department of Population under Ministry of Immigration and Population issues National Verification Card (NVC) and Citizenship Scrutiny Card (CSC).',
    active: true,
    notes: 'Household List (Form 10) lists all cohabitating family members registered with township authorities.',
  },
  {
    id: 'CTRY-LKA',
    countryName: 'Sri Lanka',
    iso2: 'LK',
    iso3: 'LKA',
    nationality: 'Sri Lankan',
    officialLanguages: 'Sinhala, Tamil, English',
    scriptsUsed: 'Sinhala, Tamil, Latin',
    transliterationNotes: 'Ge-names (household prefix) often preceding given names in Sinhala; patronymic initial formatting in Tamil.',
    namingConvention: 'compound',
    civilRegistryInfo: 'Department for Registration of Persons (DRP) and Registrar General\'s Department.',
    active: true,
    notes: 'National Identity Card (NIC) issued to citizens over 15. Form B-42 indicates registered live birth.',
  },
  {
    id: 'CTRY-PAK',
    countryName: 'Pakistan',
    iso2: 'PK',
    iso3: 'PAK',
    nationality: 'Pakistani',
    officialLanguages: 'Urdu, English',
    scriptsUsed: 'Urdu (Nastaliq), Latin',
    transliterationNotes: 'Khan, Shah, Qureshi, Chaudhry transliterations; widespread use of father\'s name as middle/last name.',
    namingConvention: 'patronymic',
    civilRegistryInfo: 'National Database and Registration Authority (NADRA) maintains centralized civil registry.',
    active: true,
    notes: 'NADRA Smart National Identity Card (SNIC) and Family Registration Certificate (FRC) provide authoritative family trees.',
  },
  {
    id: 'CTRY-SOM',
    countryName: 'Somalia',
    iso2: 'SO',
    iso3: 'SOM',
    nationality: 'Somali',
    officialLanguages: 'Somali, Arabic',
    scriptsUsed: 'Latin (Somali script), Arabic',
    transliterationNotes: 'Three-name structure (Given name + Father\'s name + Paternal grandfather\'s name); vowel doubling (e.g., Faarax/Farah).',
    namingConvention: 'patronymic',
    civilRegistryInfo: 'National Identification and Registration Authority (NIRA) established in Mogadishu; localized municipal documentation.',
    active: true,
    notes: 'Centralized registry historically disrupted; UNHCR Proof of Registration and community elder affidavits frequently utilized.',
  },
  {
    id: 'CTRY-COD',
    countryName: 'Democratic Republic of the Congo',
    iso2: 'CD',
    iso3: 'COD',
    nationality: 'Congolese (DRC)',
    officialLanguages: 'French, Lingala, Swahili, Kikongo, Tshiluba',
    scriptsUsed: 'Latin',
    transliterationNotes: 'Post-names (postnom) following given names; compound ethnic family identifiers.',
    namingConvention: 'compound',
    civilRegistryInfo: 'Office National d\'Identification de la Population (ONIP) and municipal civil registry offices (Bureau de l\'État Civil).',
    active: true,
    notes: 'Carte d\'Électeur frequently functions as primary national identity card in absence of standard national ID.',
  },
  {
    id: 'CTRY-YEM',
    countryName: 'Yemen',
    iso2: 'YE',
    iso3: 'YEM',
    nationality: 'Yemeni',
    officialLanguages: 'Arabic',
    scriptsUsed: 'Arabic',
    transliterationNotes: 'Four-part naming structure (Given + Father + Grandfather + Family/Tribal title); Al- prefix.',
    namingConvention: 'tripartite',
    civilRegistryInfo: 'Civil Status and Civil Registry Authority (CRA).',
    active: true,
    notes: 'Family Card (Bitāqat \'Ā\'iliyya) issued to household heads; National Identity Card issued at age 16.',
  }
];

export const INITIAL_COUNTRY_DOCUMENTS: CountryDocumentRecord[] = [
  // Afghanistan Documents
  {
    id: 'CDOC-AFG-01',
    countryId: 'CTRY-AFG',
    countryName: 'Afghanistan',
    documentName: 'Electronic National Identity Card (e-Tazkira)',
    localName: 'تذکره الکترونیکی',
    documentCategory: 'identity',
    issuingAuthorityDesc: 'National Statistics and Information Authority (NSIA)',
    securityFeatures: 'Polycarbonate smart card, embedded chip, biometric QR code, microprinting',
    typicalFields: 'National ID Number, Full Name, Father Name, Grandfather Name, Date of Birth, Place of Origin',
    validityPeriodDesc: 'Indefinite (Adults) / 5 Years (Minors)',
    electronicVerificationAvailable: false,
    active: true,
    notes: 'Primary authoritative identity card issued in Afghanistan since 2018.',
  },
  {
    id: 'CDOC-AFG-02',
    countryId: 'CTRY-AFG',
    countryName: 'Afghanistan',
    documentName: 'Paper National Identity Card (Kaghazi Tazkira)',
    localName: 'تذکره کاغذی',
    documentCategory: 'identity',
    issuingAuthorityDesc: 'Population Registration Department / Provincial Civil Registry',
    securityFeatures: 'Official provincial stamp, registration book reference volume/page, embossed seal',
    typicalFields: 'Volume, Page, Registration No., Full Name, Father, Grandfather, Birth Year, Physical Characteristics',
    validityPeriodDesc: 'Indefinite',
    electronicVerificationAvailable: false,
    active: true,
    notes: 'Requires provincial archive manual cross-check. Often laminated by holders.',
  },
  {
    id: 'CDOC-AFG-03',
    countryId: 'CTRY-AFG',
    countryName: 'Afghanistan',
    documentName: 'Standard Machine Readable Passport',
    localName: 'پاسپورت جمهوری اسلامی افغانستان',
    documentCategory: 'identity',
    issuingAuthorityDesc: 'General Directorate of Passports, Ministry of Interior',
    securityFeatures: 'ICAO Doc 9303 compliant, UV fluorescent ink, hologram laminate, MRZ',
    typicalFields: 'Passport No., Given Name, Surname, Father Name, Place of Birth, Date of Expiry',
    validityPeriodDesc: '5 or 10 Years',
    electronicVerificationAvailable: false,
    active: true,
    notes: 'Passports issued abroad through consular missions bear mission endorsement stamps.',
  },
  {
    id: 'CDOC-AFG-04',
    countryId: 'CTRY-AFG',
    countryName: 'Afghanistan',
    documentName: 'Marriage Certificate (Nikah Nama)',
    localName: 'نکاح خط / نکاح نامه',
    documentCategory: 'family_relationship',
    issuingAuthorityDesc: 'Supreme Court of Afghanistan / Primary Family Court',
    securityFeatures: 'Judicial court seal, judicial registration ledger number, signatures of two witnesses',
    typicalFields: 'Groom Details, Bride Details, Dowry (Mahr), Date of Marriage, Witness Names',
    validityPeriodDesc: 'Indefinite',
    electronicVerificationAvailable: false,
    active: true,
    notes: 'Authoritative primary legal evidence of spousal union.',
  },

  // Syrian Arab Republic Documents
  {
    id: 'CDOC-SYR-01',
    countryId: 'CTRY-SYR',
    countryName: 'Syrian Arab Republic',
    documentName: 'Family Book (Daftar A\'ila)',
    localName: 'دفتر عائلي',
    documentCategory: 'family_relationship',
    issuingAuthorityDesc: 'Civil Affairs Directorate, Ministry of Interior',
    securityFeatures: 'Official state seal on each member page, national registry volume and page number',
    typicalFields: 'Husband Name, Wife/Wives Names, Children Names, Birth Dates, National Numbers (Raqam Watani)',
    validityPeriodDesc: 'Updated upon life events',
    electronicVerificationAvailable: false,
    active: true,
    notes: 'Most comprehensive primary evidence of household structure, parent-child links, and marriage in Syria.',
  },
  {
    id: 'CDOC-SYR-02',
    countryId: 'CTRY-SYR',
    countryName: 'Syrian Arab Republic',
    documentName: 'National Identity Card (Bitāqat Shakhsiyya)',
    localName: 'بطاقة شخصية',
    documentCategory: 'identity',
    issuingAuthorityDesc: 'Civil Affairs Directorate, Ministry of Interior',
    securityFeatures: '11-digit national identity number (Raqam Watani), laminated holographic overlay, optical barcode',
    typicalFields: 'National Number, Full Name, Father, Mother, Date & Place of Birth, Civil Registry City/District',
    validityPeriodDesc: '10 Years',
    electronicVerificationAvailable: false,
    active: true,
    notes: 'Mandatory for all Syrian citizens aged 14 and older.',
  },
  {
    id: 'CDOC-SYR-03',
    countryId: 'CTRY-SYR',
    countryName: 'Syrian Arab Republic',
    documentName: 'Individual Civil Status Extract (Ikhraj Qayd)',
    localName: 'إخراج قيد فردي',
    documentCategory: 'civil_status',
    issuingAuthorityDesc: 'Directorate of Civil Affairs',
    securityFeatures: 'Revenue stamps, official stamp, civil registry officer signature',
    typicalFields: 'Full name, Father, Mother, Marital status, Religion, Place of registration, Date of issuance',
    validityPeriodDesc: '3 to 6 Months for administrative transactions',
    electronicVerificationAvailable: false,
    active: true,
    notes: 'Frequently requested as fresh proof of current civil status.',
  },

  // Pakistan Documents
  {
    id: 'CDOC-PAK-01',
    countryId: 'CTRY-PAK',
    countryName: 'Pakistan',
    documentName: 'Computerized National Identity Card (CNIC / Smart NIC)',
    localName: 'قومی شناختی کارڈ',
    documentCategory: 'identity',
    issuingAuthorityDesc: 'National Database and Registration Authority (NADRA)',
    securityFeatures: '13-digit unique number (XXXXX-XXXXXXX-X), embedded chip, microprinting, tactile features',
    typicalFields: 'Citizen Number, Name, Father Name, Gender, Country of Stay, Date of Birth, Date of Expiry',
    validityPeriodDesc: '10 Years',
    electronicVerificationAvailable: false,
    active: true,
    notes: 'Primary national identity document in Pakistan.',
  },
  {
    id: 'CDOC-PAK-02',
    countryId: 'CTRY-PAK',
    countryName: 'Pakistan',
    documentName: 'Family Registration Certificate (FRC)',
    localName: 'فیملی رجسٹریشن سرٹیفکیٹ',
    documentCategory: 'family_relationship',
    issuingAuthorityDesc: 'National Database and Registration Authority (NADRA)',
    securityFeatures: 'NADRA QR code verification, holographic emblem, unique tracking number',
    typicalFields: 'Family Tree: Head, Spouse, Children with CNIC/B-form numbers and relationship links',
    validityPeriodDesc: 'Valid at time of issuance',
    electronicVerificationAvailable: false,
    active: true,
    notes: 'Authoritative single-page verified household genealogy certificate.',
  },

  // Bangladesh Documents
  {
    id: 'CDOC-BGD-01',
    countryId: 'CTRY-BGD',
    countryName: 'Bangladesh',
    documentName: 'Smart National Identity Card (Smart NID)',
    localName: 'জাতীয় পরিচয়পত্র',
    documentCategory: 'identity',
    issuingAuthorityDesc: 'National Identity Registration Wing, Election Commission',
    securityFeatures: '10-digit NID number, 25-tier security features, laser engraved photo, electronic chip',
    typicalFields: 'Name, Father Name, Mother Name, Date of Birth, Blood Group, Signature',
    validityPeriodDesc: '10 Years',
    electronicVerificationAvailable: false,
    active: true,
    notes: 'Primary biometric identity credential in Bangladesh.',
  },
  {
    id: 'CDOC-BGD-02',
    countryId: 'CTRY-BGD',
    countryName: 'Bangladesh',
    documentName: 'Online Birth Registration Certificate (BRC)',
    localName: 'জন্ম নিবন্ধন সনদপত্র',
    documentCategory: 'civil_status',
    issuingAuthorityDesc: 'Office of the Registrar General, Birth and Death Registration (BDRIS)',
    securityFeatures: '17-digit birth registration number, online QR verification code',
    typicalFields: '17-digit BRN, Name, Father Name, Mother Name, Permanent Address, Place of Birth',
    validityPeriodDesc: 'Indefinite',
    electronicVerificationAvailable: false,
    active: true,
    notes: '17-digit number is verifiable via the public BDRIS verification portal.',
  },

  // Somalia Documents
  {
    id: 'CDOC-SOM-01',
    countryId: 'CTRY-SOM',
    countryName: 'Somalia',
    documentName: 'UNHCR Proof of Registration (Refugee Card / Document)',
    localName: 'Warqadda Diiwaangelinta UNHCR',
    documentCategory: 'identity',
    issuingAuthorityDesc: 'UNHCR Somalia / Federal Government Refugee Commission',
    securityFeatures: 'UNHCR seal, individual registration number, biometric photograph',
    typicalFields: 'Individual ID, Case Number, Full Name (3-part), Date of Birth, Household Members, Camp/Location',
    validityPeriodDesc: '1 to 2 Years (Renewable)',
    electronicVerificationAvailable: false,
    active: true,
    notes: 'Standard recognized identification for displaced individuals in the region.',
  },

  // Yemen Documents
  {
    id: 'CDOC-YEM-01',
    countryId: 'CTRY-YEM',
    countryName: 'Yemen',
    documentName: 'National Identity Card (Bitāqat Shakhsiyya)',
    localName: 'بطاقة شخصية يمنية',
    documentCategory: 'identity',
    issuingAuthorityDesc: 'Civil Status and Civil Registry Authority (CRA)',
    securityFeatures: '11-digit national identity number, optical scan barcode, official CRA watermark',
    typicalFields: 'National Number, Full Name (4-part), Mother Name, Place of Birth, Date of Birth, Blood Type',
    validityPeriodDesc: '10 Years',
    electronicVerificationAvailable: false,
    active: true,
    notes: 'Mandatory identification card for Yemeni citizens aged 16 and over.',
  }
];

export const INITIAL_EVIDENCE_RULES: EvidenceRuleRecord[] = [
  // Afghanistan Evidence Rules
  {
    id: 'ERULE-AFG-01',
    countryId: 'CTRY-AFG',
    countryName: 'Afghanistan',
    claimType: 'primary_identity',
    description: 'Primary Identity Verification for Afghan Applicants',
    primaryDocumentTypes: ['e_tazkira', 'passport', 'kaghazi_tazkira'],
    alternativeDocumentTypes: ['unhcr_registration', 'driving_license', 'tazkira_confirmation_letter'],
    minConfidenceThreshold: 75,
    strictness: 'flexible_humanitarian',
    verificationGuidance: 'e-Tazkira is preferred. Paper Tazkira requires careful scrutiny of provincial volume/page ledger stamps and father/grandfather names.',
    active: true,
  },
  {
    id: 'ERULE-AFG-02',
    countryId: 'CTRY-AFG',
    countryName: 'Afghanistan',
    claimType: 'parent_child',
    description: 'Parent-Child Relationship Proof for Afghan Families',
    primaryDocumentTypes: ['tazkira_showing_father', 'e_tazkira_family_section', 'birth_certificate'],
    alternativeDocumentTypes: ['unhcr_family_manifest', 'court_paternity_ruling', 'joint_community_affidavit'],
    minConfidenceThreshold: 70,
    strictness: 'flexible_humanitarian',
    verificationGuidance: 'Afghan Tazkira records explicitly name the father and paternal grandfather, providing direct lineage evidence.',
    active: true,
  },
  {
    id: 'ERULE-AFG-03',
    countryId: 'CTRY-AFG',
    countryName: 'Afghanistan',
    claimType: 'spousal_union',
    description: 'Spousal Union Verification for Afghan Spouses',
    primaryDocumentTypes: ['nikah_nama', 'marriage_certificate'],
    alternativeDocumentTypes: ['joint_unhcr_registration', 'court_marriage_endorsement', 'joint_affidavit'],
    minConfidenceThreshold: 70,
    strictness: 'flexible_humanitarian',
    verificationGuidance: 'Nikah Nama should be issued or registered by a primary family court with witness signatures.',
    active: true,
  },

  // Syrian Arab Republic Evidence Rules
  {
    id: 'ERULE-SYR-01',
    countryId: 'CTRY-SYR',
    countryName: 'Syrian Arab Republic',
    claimType: 'parent_child',
    description: 'Parent-Child Evidence for Syrian Families',
    primaryDocumentTypes: ['family_book', 'birth_certificate', 'individual_civil_status_extract'],
    alternativeDocumentTypes: ['unhcr_registration', 'hospital_birth_record', 'family_registry_extract'],
    minConfidenceThreshold: 75,
    strictness: 'standard',
    verificationGuidance: 'Family Book (Daftar A\'ila) lists all children under the father\'s record with individual national numbers.',
    active: true,
  },
  {
    id: 'ERULE-SYR-02',
    countryId: 'CTRY-SYR',
    countryName: 'Syrian Arab Republic',
    claimType: 'primary_identity',
    description: 'Primary Identity Verification for Syrian Applicants',
    primaryDocumentTypes: ['passport', 'national_id', 'individual_civil_status_extract'],
    alternativeDocumentTypes: ['family_book_page', 'unhcr_registration', 'syrian_driving_license'],
    minConfidenceThreshold: 75,
    strictness: 'standard',
    verificationGuidance: 'Verify 11-digit national identity number (Raqam Watani) consistency across all submitted Syrian documents.',
    active: true,
  },

  // Pakistan Evidence Rules
  {
    id: 'ERULE-PAK-01',
    countryId: 'CTRY-PAK',
    countryName: 'Pakistan',
    claimType: 'parent_child',
    description: 'Parent-Child Evidence for Pakistani Families',
    primaryDocumentTypes: ['family_registration_certificate', 'nadra_birth_certificate', 'child_b_form'],
    alternativeDocumentTypes: ['hospital_birth_record', 'school_leaving_certificate', 'unhcr_registration'],
    minConfidenceThreshold: 80,
    strictness: 'standard',
    verificationGuidance: 'NADRA Family Registration Certificate (FRC) by birth or marriage provides authoritative lineage data.',
    active: true,
  }
];

export const INITIAL_VERIFICATION_AUTHORITIES: VerificationAuthorityRecord[] = [
  {
    id: 'AUTH-UNHCR-01',
    authorityName: 'UNHCR Identity & Registration Section (RAAS)',
    jurisdiction: 'International Agency',
    verificationMethod: 'MANUAL_REQUEST',
    apiAvailable: false,
    contactEmail: 'hqreg@unhcr.org',
    contactPortalUrl: 'https://www.unhcr.org/registration',
    responseSlaDays: 7,
    active: true,
    notes: 'UNHCR Refugee Registration and Identity verification via secure bilateral liaison channel.',
  },
  {
    id: 'AUTH-AFG-NSIA',
    authorityName: 'Afghanistan National Statistics and Information Authority (NSIA)',
    countryId: 'CTRY-AFG',
    countryName: 'Afghanistan',
    jurisdiction: 'National Civil Registry',
    verificationMethod: 'REFERENCE_ONLY',
    apiAvailable: false,
    contactEmail: 'info@nsia.gov.af',
    contactPortalUrl: 'https://nsia.gov.af',
    responseSlaDays: 21,
    active: true,
    notes: 'Reference document comparison only. Direct state contact subject to strict refugee protection review.',
  },
  {
    id: 'AUTH-SYR-CIVIL',
    authorityName: 'Syrian Directorate of Civil Affairs Archive Reference',
    countryId: 'CTRY-SYR',
    countryName: 'Syrian Arab Republic',
    jurisdiction: 'Civil Status Administration',
    verificationMethod: 'REFERENCE_ONLY',
    apiAvailable: false,
    contactEmail: '',
    contactPortalUrl: '',
    responseSlaDays: 30,
    active: true,
    notes: 'Reference archive examination only. Direct contact with origin authorities is prohibited without explicit protection clearance.',
  },
  {
    id: 'AUTH-BGD-BDRIS',
    authorityName: 'Bangladesh Birth & Death Registration Information System (BDRIS)',
    countryId: 'CTRY-BGD',
    countryName: 'Bangladesh',
    jurisdiction: 'National Portal Reference',
    verificationMethod: 'AUTHORIZED_API',
    apiAvailable: false,
    contactEmail: 'support@bdris.gov.bd',
    contactPortalUrl: 'https://bdris.gov.bd/certificate/verify',
    responseSlaDays: 5,
    active: true,
    notes: 'Online portal provides manual verification using 17-digit Birth Registration Number and date of birth.',
  },
  {
    id: 'AUTH-PAK-NADRA',
    authorityName: 'NADRA Verification Service Directorate',
    countryId: 'CTRY-PAK',
    countryName: 'Pakistan',
    jurisdiction: 'National Identity Database',
    verificationMethod: 'MANUAL_REQUEST',
    apiAvailable: false,
    contactEmail: 'verification@nadra.gov.pk',
    contactPortalUrl: 'https://www.nadra.gov.pk',
    responseSlaDays: 14,
    active: true,
    notes: 'Manual verification requests for identity certificates through authorized consular liaison.',
  }
];

export const INITIAL_VERIFICATION_REQUESTS: VerificationRequestRecord[] = [
  {
    id: 'VREQ-001',
    requestId: 'VR-2026-081240',
    familyId: 'FAM-2026-000001',
    applicationId: 'APP-2026-000001',
    familyName: 'Al-Hassan Family',
    memberId: 'MEM-01-HEAD',
    memberName: 'Ahmad Al-Hassan',
    documentId: 'DOC-01-PASSPORT',
    documentName: 'Passport_Ahmad_AlHassan.pdf',
    countryId: 'CTRY-SYR',
    countryName: 'Syrian Arab Republic',
    countryDocumentId: 'CDOC-SYR-01',
    countryDocumentName: 'Family Book (Daftar A\'ila)',
    authorityId: 'AUTH-UNHCR-01',
    authorityName: 'UNHCR Identity & Registration Section (RAAS)',
    requestType: 'unhcr_crosscheck',
    status: 'verified',
    consentRequired: true,
    consentStatus: 'granted',
    protectionReviewRequired: true,
    protectionReviewStatus: 'cleared_safe_to_contact',
    assignedOfficer: 'Sarah Jenkins',
    dispatchedAt: '2026-08-14',
    completedAt: '2026-08-15',
    outcomeSummary: 'UNHCR RAAS cross-check confirmed matching registration number and listed dependents.',
    officerNotes: 'Bilateral confirmation received via secure liaison token.',
    createdAt: '2026-08-14T10:00:00Z',
  }
];
