"""
Generic Post-Processing & Bidirectional Normalization Layer for Standalone EasyOCR.

Provides:
- Unicode-based script direction detection (RTL vs LTR)
- Line clustering and reading-order bounding-box sorting (RTL: right-to-left; LTR: left-to-right)
- Visual-to-logical Unicode order restoration via standard bidirectional algorithm
- Stray OCR segmentation noise cleanup
- Preservation of untouched raw EasyOCR outputs alongside normalized fields

Strictly generic: No language-code branching (no `if lang == 'ar'`, etc.).
"""

import unicodedata
from typing import List, Tuple, Dict, Any
from bidi import get_display


def is_rtl_text(text: str) -> bool:
    """
    Determine whether text is predominantly written in a Right-to-Left script.
    Inspects Unicode bidirectional categories without language assumptions.
    Strong RTL types: 'R' (Hebrew, etc.), 'AL' (Arabic Letter).
    Strong LTR types: 'L' (Latin, Cyrillic, Greek, Devanagari, etc.).
    """
    rtl_count = 0
    ltr_count = 0
    for ch in text:
        bidi_cat = unicodedata.bidirectional(ch)
        if bidi_cat in ('R', 'AL'):
            rtl_count += 1
        elif bidi_cat == 'L':
            ltr_count += 1
    return rtl_count > ltr_count and rtl_count > 0


def normalize_bidirectional_text(text: str) -> str:
    """
    Restore standard logical Unicode ordering for text recognized in visual order.

    EasyOCR applies `get_display()` internally on RTL models, producing visual
    presentation order (intended for naive LTR terminals). In standard Unicode,
    modern web browsers and APIs require logical order.

    Applying the bidirectional transform inverts visual layout back to standard
    logical character sequences.
    """
    if not is_rtl_text(text):
        return text.strip()

    # Inverse visual-to-logical transformation via Unicode Bidirectional Algorithm
    logical = get_display(text)

    # Clean stray OCR segmentation noise artifacts commonly generated by EasyOCR:
    # - vertical bars '|' generated from disconnected alif/lam stems
    # - stray carets '^'
    cleaned = logical.replace('|', '').replace('^', '')

    # Collapse redundant consecutive spaces
    cleaned = ' '.join(cleaned.split())
    return cleaned.strip()


def reconstruct_lines_and_reorder(
    raw_results: List[Tuple[Any, str, float]],
    y_threshold_ratio: float = 0.5
) -> List[Dict[str, Any]]:
    """
    Cluster raw bounding-box detections into logical lines and sort items
    in natural reading order (Right-to-Left for RTL scripts, Left-to-Right for LTR).

    Args:
        raw_results: List of (bbox, raw_text, confidence) from EasyOCR.
        y_threshold_ratio: Relative vertical tolerance for clustering boxes into a single line.

    Returns:
        List of structured line dictionaries containing normalized text, raw text,
        confidence, and line bounding box.
    """
    if not raw_results:
        return []

    # Prepare intermediate items with centroid geometry
    items = []
    for bbox, text, conf in raw_results:
        clean_text = str(text).strip()
        if not clean_text:
            continue
        xs = [pt[0] for pt in bbox]
        ys = [pt[1] for pt in bbox]
        min_x, max_x = min(xs), max(xs)
        min_y, max_y = min(ys), max(ys)
        cy = (min_y + max_y) / 2.0
        cx = (min_x + max_x) / 2.0
        h = max(1.0, max_y - min_y)
        items.append({
            "bbox": [[float(pt[0]), float(pt[1])] for pt in bbox],
            "raw_text": clean_text,
            "conf": float(conf),
            "min_x": min_x,
            "max_x": max_x,
            "min_y": min_y,
            "max_y": max_y,
            "cx": cx,
            "cy": cy,
            "h": h
        })

    if not items:
        return []

    # Sort items primarily from top to bottom
    items.sort(key=lambda it: it["cy"])

    # Cluster into horizontal lines
    lines_clusters: List[List[Dict[str, Any]]] = []
    current_cluster: List[Dict[str, Any]] = [items[0]]
    avg_h = items[0]["h"]

    for it in items[1:]:
        last_cy = sum(c["cy"] for c in current_cluster) / len(current_cluster)
        y_tol = max(avg_h, it["h"]) * y_threshold_ratio
        if abs(it["cy"] - last_cy) <= y_tol:
            current_cluster.append(it)
        else:
            lines_clusters.append(current_cluster)
            current_cluster = [it]
            avg_h = it["h"]
    if current_cluster:
        lines_clusters.append(current_cluster)

    structured_lines: List[Dict[str, Any]] = []

    for cluster in lines_clusters:
        combined_raw = " ".join(c["raw_text"] for c in cluster)
        rtl_line = is_rtl_text(combined_raw)

        # Sort items along horizontal axis according to script reading direction
        if rtl_line:
            # Right-to-Left: rightmost box first (descending cx / min_x)
            cluster.sort(key=lambda c: c["cx"], reverse=True)
        else:
            # Left-to-Right: leftmost box first (ascending cx / min_x)
            cluster.sort(key=lambda c: c["cx"])

        # Compute enclosing bounding box
        all_x = [pt[0] for c in cluster for pt in c["bbox"]]
        all_y = [pt[1] for c in cluster for pt in c["bbox"]]
        enclosing_box = [
            [float(min(all_x)), float(min(all_y))],
            [float(max(all_x)), float(min(all_y))],
            [float(max(all_x)), float(max(all_y))],
            [float(min(all_x)), float(max(all_y))]
        ]

        # Raw combined line text
        line_raw_text = " ".join(c["raw_text"] for c in cluster)
        avg_conf = round(sum(c["conf"] for c in cluster) / len(cluster), 4)

        # Apply bidirectional normalization
        if rtl_line:
            line_normalized_text = normalize_bidirectional_text(line_raw_text)
        else:
            line_normalized_text = " ".join(line_raw_text.split())

        # Collect word items with individual normalized and raw representations
        word_items = []
        for c in cluster:
            tok_raw = c["raw_text"]
            tok_norm = normalize_bidirectional_text(tok_raw) if rtl_line else tok_raw
            for w in tok_norm.split():
                word_items.append({
                    "text": w,
                    "confidence": round(c["conf"], 4),
                    "bounding_box": c["bbox"]
                })

        structured_lines.append({
            "text": line_normalized_text,
            "raw_text": line_raw_text,
            "confidence": avg_conf,
            "bounding_box": enclosing_box,
            "words": word_items
        })

    return structured_lines
